---
spring:
  datasource:
    password: 5bdfcc99da3d957eb7dd4bd7b
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-eb1c972d-85ed-4cbd-b49c-4b0979d51536.cqryblsdrbcs.us-east-1.rds.amazonaws.com:7300/postgres
    username: 5c03c30d9e7a
  config:
    activate:
      on-profile: default
cds:
  data-source:
    auto-config:
      enabled: false
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
